# Generated by Django 4.1.1 on 2022-09-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='podcast_name',
            field=models.CharField(max_length=125),
        ),
    ]
